blank_issues_enabled: true
contact_links:
  - name: Accelerate community chat
    about: Community chat room
    url: https://gitter.im/AccelerateHS/Lobby
  - name: Accelerate mailing list
    about: Please ask and answer questions here
    url: mailto:accelerate-haskell@googlegroups.com

