name: CI

# Trigger the workflow on push or pull request
on:
  pull_request:
  push:
    # but only for the master branch
    # branches: [master]

jobs:
  stack:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        stack: ["latest"]
        ghc:
          - "8.8"
          - "8.6"
          - "8.4"
          - "8.2"
        exclude:
          - os: macOS-latest
            ghc: 8.6
          - os: macOS-latest
            ghc: 8.4
          - os: macOS-latest
            ghc: 8.2
          - os: windows-latest
            ghc: 8.6
          - os: windows-latest
            ghc: 8.4
          - os: windows-latest
            ghc: 8.2
        env:
          - flags: "--system-ghc --jobs 1 --flag accelerate:nofib"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        enable-stack: true
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        ln -s stack-${{ matrix.ghc }}.yaml stack.yaml
        stack build ${{ flags }} --test --no-run-tests

    - name: Test
      run: |
        stack test accelerate:doctest ${{ flags }}
        stack test accelerate:nofib-interpreter ${{ flags }} --test-arguments='--hedgehog-tests 25'

